version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name codedeploy --s3-location s3://mybucket-codepipeline20250918/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src